spring.application.name=mycloud-storage-webservice


server.port=8080
spring.datasource.url=jdbc:postgresql://localhost:5432/thenichedb_prd
spring.datasource.username=the_niche_app
spring.datasource.password=the_niche_11223344556677
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.hibernate.properties.format_sql=true

logging.level.org.hibernate.SQL= DEBUG


logging.level.org.springframework.security=DEBUG



#jwt-configuration
app.jwt-secret=daf66e01593f61a15b857cf433aae03a005812b31234e149036bcc8dee755dbb
# expired in 7 days
app-jwt-expiration-milliseconds=604800000
